# Generated by Django 2.2.3 on 2019-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails1',
            name='otp',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customerdetails1',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails1',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
