# Generated by Django 2.2.3 on 2019-11-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20191108_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Merchant')),
            ],
        ),
    ]
