# Generated by Django 2.2.3 on 2019-11-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mid',
        ),
    ]
