# Generated by Django 2.2.3 on 2019-11-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_product_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='emailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
