# Generated by Django 2.2.3 on 2019-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20191123_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='otp',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
