# Generated by Django 2.2.3 on 2019-11-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20191123_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
        migrations.AddField(
            model_name='product',
            name='mid',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Merchant'),
        ),
    ]
